import Link from "next/link";
import { Suspense } from "react";
import { AuthForm } from "@/components/AuthForm";
import { PUBLIC_TESTING_NOTICE } from "@/lib/playtest-agreement";
import styles from "../auth.module.css";

export default function RegisterPage() {
  return <main id="main" className={`${styles.authPage} shell`}><section className={`${styles.authShell} ${styles.registerShell}`} aria-labelledby="register-title"><aside className={styles.contextPanel}><div><p className="eyebrow">Field registration</p><h2>Create your access record.</h2><p>An account keeps your submitted games and Lab activity connected to one identity.</p></div><ol className={styles.steps}><li><span>01</span><div><strong>Create account</strong><p>Provide a display name, email, and secure password.</p></div></li><li><span>02</span><div><strong>Verify email</strong><p>Use the confirmation message sent to your inbox.</p></div></li><li><span>03</span><div><strong>Receive access</strong><p>Invite-only Arena entry still requires playtester approval.</p></div></li></ol></aside><div className={styles.formPanel}><header><p className="eyebrow">PodBound account</p><h1 id="register-title">Create an account</h1><p>Registration does not automatically grant invite-only Arena access.</p></header><div className={styles.testingNotice}><strong>Temporary public simulator test</strong><p>{PUBLIC_TESTING_NOTICE}</p><p>By creating an account, you agree to the <Link href="/terms">Terms of Use</Link> and acknowledge the <Link href="/privacy">Privacy Policy</Link>. The current playtest agreement must also be accepted before simulator entry.</p></div><Suspense><AuthForm mode="register" /></Suspense><nav className={styles.authLinks} aria-label="Registration help"><Link href="/sign-in">Already registered? Sign in</Link><Link href="/testing-disclaimer">Testing Disclaimer</Link></nav></div></section></main>;
}
